#!/bin/bash


echo "$1"
case "$1" in 

	"stop")
		docker stack rm redis
		;;

	"build")
		docker compose build
		;;

	"logs")
		docker service logs --tail 100 --follow --raw redis_cluster_adm
		;;

	"logs-node1")
		docker service logs --tail 100 --follow --raw redis_node1
		;;

	"logs-node2")
		docker service logs --tail 100 --follow --raw redis_node2
		;;

	"logs-node3")
		docker service logs --tail 100 --follow --raw redis_node3
		;;

	"logs-node4")
		docker service logs --tail 100 --follow --raw redis_node4
		;;

	"logs-node5")
		docker service logs --tail 100 --follow --raw redis_node5
		;;

	"logs-node6")
		docker service logs --tail 100 --follow --raw redis_node6
		;;

	"logs-app")
		docker service logs --tail 100 --follow --raw redis_cluster_app
		;;

	"deploy")
		docker stack deploy --with-registry-auth -c stack-redis-new.yaml redis
		;;

esac

