version: '3.7'

#https://bpaulino.com/entries/how-to-use-redis-cluster-for-caching

services:

  node1:
    container_name: node1
    hostname: node1
    image: redis_cluster:1.0
    environment:
      REDIS_PORT: 6381
      SERVER_ADM_PORT: 50000
      NODE_ADM_PORT: 50000
    expose:
      - "6381" 
    networks:
      - net_overlay
    deploy:
      endpoint_mode: dnsrr      
    volumes:
      - ./src:/main

  node2:
    container_name: node2
    hostname: node2
    image: redis_cluster:1.0
    environment:
      REDIS_PORT: 6382
      SERVER_ADM_PORT: 50000
      NODE_ADM_PORT: 50000
    expose:
      - "6382" 
    networks:
      - net_overlay
    deploy:
      endpoint_mode: dnsrr      
    volumes:
      - ./src:/main

  node3:
    container_name: node3
    hostname: node3
    image: redis_cluster:1.0
    environment:
      REDIS_PORT: 6383
      SERVER_ADM_PORT: 50000
      NODE_ADM_PORT: 50000
    expose:
      - "6383" 
    networks:
      - net_overlay
    deploy:
      endpoint_mode: dnsrr      
    volumes:
      - ./src:/main

  node4:
    container_name: node4
    hostname: node4
    image: redis_cluster:1.0
    environment:
      REDIS_PORT: 6384
      SERVER_ADM_PORT: 50000
      NODE_ADM_PORT: 50000
    expose:
      - "6384" 
    networks:
      - net_overlay
    deploy:
      endpoint_mode: dnsrr      
    volumes:
      - ./src:/main

  node5:
    container_name: node5
    hostname: node5
    image: redis_cluster:1.0
    environment:
      REDIS_PORT: 6385
      SERVER_ADM_PORT: 50000
      NODE_ADM_PORT: 50000
    expose:
      - "6385" 
    networks:
      - net_overlay
    deploy:
      endpoint_mode: dnsrr      
    volumes:
      - ./src:/main

  node6:
    container_name: node6
    hostname: node6
    image: redis_cluster:1.0
    environment:
      REDIS_PORT: 6386
      SERVER_ADM_PORT: 50000
      NODE_ADM_PORT: 50000
    expose:
      - "6386" 
    networks:
      - net_overlay
    deploy:
      endpoint_mode: dnsrr      
    volumes:
      - ./src:/main

  cluster_adm:
    container_name: cluster_adm
    hostname: cluster_adm
    image: redis_cluster:1.0
    environment:
      CLUSTER_NODES: 'node1:6381,node2:6382,node3:6383,node4:6384,node5:6385,node6:6386'
      SERVER_ADM_PORT: 50000
      NODE_ADM_PORT: 50000
      CLUSTER_ADM: 'yes'
      REDIS_PORT: 6379
      #NODES: "node1:6381,node2:6382,node3:6383,node4:6384,node5:6385,node6:6386"
    tty: true
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6      
    networks:
      - net_overlay
    deploy:
      endpoint_mode: dnsrr      
    volumes:
      - ./src:/main

  cluster_app:
    container_name: cluster_app
    hostname: cluster_app
    image: cluster_app:1.1
    environment:
      PORT: 3000
      NODE_ENV: production
      REDIS_CLUSTER_NODES: 'node1:6381,node2:6382,node3:6383,node4:6384,node5:6385,node6:6386,cluster_adm:6379'
    depends_on:
      - node1
      - node2
      - node3
      - node4
      - node5
      - node6
      - cluster_adm
    ports:
      - "3000:3000"
    networks:
      - net_overlay

networks:
  net_overlay:
    external: true             
